/**
 * `clawy-agent init` — interactive config file generator.
 *
 * Prompts the user for LLM provider, model, and API key env var, then
 * writes a clawy-agent.yaml file to the current directory.
 */

import fs from "node:fs";
import readline from "node:readline";
import { configFilePath } from "./config.js";

const PROVIDERS = ["anthropic", "openai", "google"] as const;

const DEFAULT_MODELS: Record<string, string> = {
  anthropic: "claude-sonnet-4-6",
  openai: "gpt-4o",
  google: "gemini-2.5-pro",
};

const DEFAULT_ENV_VARS: Record<string, string> = {
  anthropic: "ANTHROPIC_API_KEY",
  openai: "OPENAI_API_KEY",
  google: "GOOGLE_API_KEY",
};

function ask(
  rl: readline.Interface,
  question: string,
): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => resolve(answer.trim()));
  });
}

function generateConfig(opts: {
  provider: string;
  model: string;
  apiKeyEnvVar: string;
  name: string;
}): string {
  return `# Clawy Agent Configuration
# Generated by "clawy-agent init"

# LLM Provider
llm:
  provider: ${opts.provider}
  model: ${opts.model}
  apiKey: \${${opts.apiKeyEnvVar}}

# Channels (uncomment to enable)
# channels:
#   telegram:
#     token: \${TELEGRAM_BOT_TOKEN}
#   discord:
#     token: \${DISCORD_BOT_TOKEN}
#   webhook:
#     url: https://your-app.com/webhook
#     secret: \${WEBHOOK_SECRET}

# Hooks
hooks:
  builtin:
    factGrounding: true
    preRefusalVerifier: true
    workspaceAwareness: true
    sessionResume: true
    discipline: false

# Memory
memory:
  enabled: true
  compaction: true

# Workspace directory
workspace: ./workspace

# Agent identity
identity:
  name: "${opts.name}"
  instructions: "You are a helpful coding assistant."
`;
}

export async function runInit(): Promise<void> {
  const outPath = configFilePath();

  // Check if config already exists
  if (fs.existsSync(outPath)) {
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    });
    const overwrite = await ask(
      rl,
      `\x1b[33mclawy-agent.yaml already exists.\x1b[0m Overwrite? (y/N) `,
    );
    if (overwrite.toLowerCase() !== "y") {
      rl.close();
      console.log("Aborted.");
      return;
    }
    rl.close();
  }

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  console.log("");
  console.log("\x1b[1mClawy Agent — Configuration\x1b[0m");
  console.log("");

  // Provider
  const providerInput = await ask(
    rl,
    `LLM provider (${PROVIDERS.join(" / ")}) [\x1b[2manthropic\x1b[0m]: `,
  );
  const provider = PROVIDERS.includes(providerInput as typeof PROVIDERS[number])
    ? providerInput
    : "anthropic";

  // Model
  const defaultModel = DEFAULT_MODELS[provider] ?? "claude-sonnet-4-6";
  const modelInput = await ask(
    rl,
    `Model [\x1b[2m${defaultModel}\x1b[0m]: `,
  );
  const model = modelInput || defaultModel;

  // API key env var
  const defaultEnvVar = DEFAULT_ENV_VARS[provider] ?? "LLM_API_KEY";
  const envVarInput = await ask(
    rl,
    `API key env variable [\x1b[2m${defaultEnvVar}\x1b[0m]: `,
  );
  const apiKeyEnvVar = envVarInput || defaultEnvVar;

  // Agent name
  const nameInput = await ask(
    rl,
    `Agent name [\x1b[2mClawy Agent\x1b[0m]: `,
  );
  const name = nameInput || "Clawy Agent";

  rl.close();

  const content = generateConfig({
    provider,
    model,
    apiKeyEnvVar,
    name,
  });

  fs.writeFileSync(outPath, content, "utf-8");

  console.log("");
  console.log(`\x1b[32mCreated\x1b[0m ${outPath}`);
  console.log("");
  console.log(`Next steps:`);
  console.log(`  1. Set your API key:  export ${apiKeyEnvVar}=sk-...`);
  console.log(`  2. Start interactive: clawy-agent start`);
  console.log(`  3. Or run as server:  clawy-agent serve --port 8080`);
  console.log("");
}
